### DISCUSSION TITLE
Storing JSON values directly in record bodies

### DISCUSSION THREAD

**Discussion by spearcat** [lexicon-community/lexicon#15] [Ideas]
When working on [obsidat](https://github.com/obsidat/obsidat.github.io) I came upon a very specific limitation. I needed to store JSON values in a record. The `unknown` type exists but it does not allow certain value types, like floats. I could serialize the JSON as-is, but this led to a JSON-in-JSON-string problem. I will probably move away from trying to store JSON in a record at all, but I created these lexicons before giving up on that idea.

It's obviously not space-efficient or easy to generate or parse, and it's kind of terrible in general, so it's probably not worth having at all, but I'm posting it here to see what the community thinks of it (or for shock value).

YAML lexicon representation:

```yaml
lexicon: 1
id: io.github.obsidat.generic
defs:
  generic:
    description: >-
      Represents a union of generic JSON-compatible types.
    type: object
    properties:
      value:
        type: union
        closed: true
        refs:
          - io.github.obsidat.generic#string
          - io.github.obsidat.generic#number
          - io.github.obsidat.generic#object
          - io.github.obsidat.generic#array
          - io.github.obsidat.generic#null
        description: >-
          The value.
          A value of `undefined` is represented by a property with a value missing or `undefined`.

  keyValuePair:
    type: object
    required:
      - key
    description: >-
      Represents a key-value mapping whose value is a union of generic JSON-compatible types.
    properties:
      key:
        type: string
        description: >-
          The key for this key-value mapping.
      value:
        type: union
        closed: true
        refs:
          - io.github.obsidat.generic#string
          - io.github.obsidat.generic#number
          - io.github.obsidat.generic#object
          - io.github.obsidat.generic#array
          - io.github.obsidat.generic#null
        description: >-
          The value for this key-value mapping.
          A value of `undefined` is represented by a property with a value missing or `undefined`.

  stringIntMapping:
    type: object
    required:
      - key
    description: >-
      Represents a key-value mapping whose key is a string and whose value is an integer.
    properties:
      key:
        type: string
        description: >-
          The key for this key-value mapping.
      value:
        type: integer
        description: >-
          The value for this key-value mapping.

  string:
    type: object
    description: A generic string value, boxed for unions.
    required:
      - value
    properties:
      value:
        type: string
        description: The string.

  number:
    type: object
    description: A generic JSON number value, serialized as a string.
    required:
      - value
    properties:
      value:
        type: string
        description: The number, encoded in JSON number format.

  object:
    type: object
    description: A generic JSON object value, serialized as an array of key-value pairs.
    required:
      - value
    properties:
      value:
        type: array
        items:
          type: ref
          ref: io.github.obsidat.generic#keyValuePair
        description: The key-value pairs that comprise this object.

  array:
    type: object
    description: A generic JSON array value, serialized as an array of key-value pairs.
    required:
      - value
    properties:
      value:
        type: array
        items:
          type: ref
          ref: io.github.obsidat.generic#generic
        description: The values that comprise this array.

  undefined:
    type: object
    description: >-
      A generic undefined value, boxed for unions.
      This is a marker type, and only its `$type` property is meaningful.
      Most unions are expected to use an optional property for representing `undefined`,
      however this type is also available for completeness.
    properties: {}

  'null':
    type: object
    description: >-
      A generic null value, boxed for unions.
      This is a marker type, and only its `$type` property is meaningful.
    properties: {}
```

JSON version: [generic.json](https://github.com/user-attachments/files/18045959/generic.json)

TypeScript code to serialize into this ridiculous format (using atcute):

```ts
export function toKeyValuePairs(data?: undefined): undefined;
export function toKeyValuePairs(data: Record<string, unknown>): IoGithubObsidatGeneric.KeyValuePair[];
export function toKeyValuePairs(data?: Record<string, unknown>): IoGithubObsidatGeneric.KeyValuePair[] | undefined;
export function toKeyValuePairs(data?: Record<string, unknown>): IoGithubObsidatGeneric.KeyValuePair[] | undefined {
    if (!data) return undefined;
    return Object.entries(data).map(toKeyValuePair);
}

export function toKeyValuePair(data: [key: string, value: unknown]): IoGithubObsidatGeneric.KeyValuePair {
    return {
        key: data[0],
        value: toGenericValue(data[1]),
    } satisfies IoGithubObsidatGeneric.KeyValuePair;
}

export function toGenericValue(value: unknown): Brand.Union<
    | IoGithubObsidatGeneric.Null
    | IoGithubObsidatGeneric.Number
    | IoGithubObsidatGeneric.Object
    | IoGithubObsidatGeneric.String
    | IoGithubObsidatGeneric.Array
> | undefined {
    if (value === undefined) return undefined;
    if (value === null) return { $type: 'io.github.obsidat.generic#null' };
    if (typeof value === 'number') return {
        $type: 'io.github.obsidat.generic#number',
        value: JSON.stringify(value),
    };
    if (typeof value === 'string') return {
        $type: 'io.github.obsidat.generic#string',
        value,
    };
    if (Array.isArray(value)) return {
        $type: 'io.github.obsidat.generic#array',
        value: value.map(toGenericValue).map(e => ({
            value: e
        } satisfies IoGithubObsidatGeneric.Generic)),
    };
    if (typeof value === 'object') return {
        $type: 'io.github.obsidat.generic#object',
        value: toKeyValuePairs(value as Record<string, unknown>),
    };
    throw new Error('Unsupported type: ' + typeof value);
}
```
